apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "prometheus-elector.labels" . | nindent 4 }}
  name: {{ template "prometheus-elector.configMapName" . }}
data:
{{ toYaml .Values.configFiles | indent 2}}
