---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-elector.fullname" . }}
  labels:
    {{- include "prometheus-elector.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "prometheus-elector.selectorLabels" . | nindent 4 }}
{{- if .Values.enableLeaderProxy }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-elector.fullname" . }}-leader
  labels:
    {{- include "prometheus-elector.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-elector
  selector:
    {{- include "prometheus-elector.selectorLabels" . | nindent 4 }}
{{- end }}
